---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: ns-annotated-namespace
  labels:
    app: alpine
spec:
  containers:
    - name: alpine
      image: alpine:3.15.0
      imagePullPolicy: IfNotPresent
      stdin: true
      tty: true
