---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-annotated-namespace

resources:
  - netsvc.yaml
  - namespace.yaml

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/nse-kernel?ref=7038804b970afb9816e5ee1fb2e312be819808e6

patchesStrategicMerge:
  - patch-nse.yaml
