---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

resources:
  - namespace.yaml

bases:
  - ../../../basic

patchesStrategicMerge:
  - patch-nsmgr.yaml
  - patch-forwarder.yaml
