---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=dd875e768190907804ee83ca1412eae997d67871
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=dd875e768190907804ee83ca1412eae997d67871

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
