---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=49b796b3fac61f2ca634386eb686b0ebcaee6abf
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=49b796b3fac61f2ca634386eb686b0ebcaee6abf
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=49b796b3fac61f2ca634386eb686b0ebcaee6abf

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/49b796b3fac61f2ca634386eb686b0ebcaee6abf/examples/features/vl3-basic/vl3-netsvc.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/49b796b3fac61f2ca634386eb686b0ebcaee6abf/examples/features/vl3-basic/nsc-patch.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/49b796b3fac61f2ca634386eb686b0ebcaee6abf/examples/features/vl3-basic/nse-patch.yaml
