---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3-interdomain

resources:
  - namespace.yaml
  - autoscale-netsvc.yaml

bases:
- ../../../../../apps/nsc-kernel

patchesStrategicMerge:
- nsc-patch.yaml
- supplier-patch.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap
    files:
      - ./pod-template.yaml