---
name: Link Checker
on:
  pull_request:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Release'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    container:
      image: lycheeverse/lychee:20211216183321587853
      env:
        GITHUB_TOKEN: $LYCHEE_GITHUB_TOKEN
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check external links using lychee
        run: |
          lychee -v '**/*.md' --exclude-mail --exclude '.*?ref=.*||*127.0.0.1*||*localhost*'
